from sqlmodel import Session, select
from fastapi import HTTPException
from src.models.product_model import Product
from src.dto.product_schema import CreateProductRequest, UpdateProductRequest
from src.interfaces.catalog_repository_interface import ICatalogRepository

class CatalogRepository(ICatalogRepository):
    def __init__(self, session: Session):
        self.session = session
        
    def create(self, data: CreateProductRequest) -> Product:
        # Convert Pydantic request to SQLModel database entity
        db_product = Product(**data.model_dump())
        self.session.add(db_product)
        self.session.commit()
        # Refresh grabs the auto-incremented ID generated by Postgres
        self.session.refresh(db_product)
        return db_product

    def update(self, product_id: int, data: UpdateProductRequest) -> Product:
        db_product = self.find_one(product_id)
        
        # Only update fields that were actually provided in the request
        update_data = data.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(db_product, key, value)
            
        self.session.add(db_product)
        self.session.commit()
        self.session.refresh(db_product)
        return db_product

    def delete(self, product_id: int):
        db_product = self.find_one(product_id)
        self.session.delete(db_product)
        self.session.commit()
        return db_product

    def find(self, limit: int, offset: int) -> list[Product]:
        # Equivalent to Prisma findMany({ take: limit, skip: offset })
        statement = select(Product).offset(offset).limit(limit)
        results = self.session.exec(statement).all()
        return list(results)

    def find_one(self, product_id: int) -> Product:
        db_product = self.session.get(Product, product_id)
        if not db_product:
            # Equivalent to your NotFoundError
            raise HTTPException(status_code=404, detail="Product not found")
        return db_product

    def find_stock(self, ids: list[int]) -> list[Product]:
        # Equivalent to Prisma where { id: { in: ids } }
        statement = select(Product).where(Product.id.in_(ids))
        results = self.session.exec(statement).all()
        return list(results)
